{% set name = "dbgpy" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbgpy-{{ version }}.tar.gz
  sha256: b2c31671e723378a99e4996205c5deb41dd85e10349cce0013be67e098ba2660

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - astunparse >=1,<2  # [py<39]
    - attrs >=21.1,<22.0
    - python

test:
  imports:
    - dbgpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marcelroed/dbgpy
  summary: Python implementation of Rust's dbg! macro
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelroed
